# Generated by Django 3.2.8 on 2022-03-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAddress',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('local_ip', models.GenericIPAddressField()),
                ('netmask', models.CharField(max_length=255, verbose_name='子网掩码')),
                ('gateway', models.CharField(max_length=255, verbose_name='网关地址')),
                ('location', models.CharField(max_length=255, verbose_name='本级平台名称')),
                ('loc_des', models.CharField(max_length=255, verbose_name='本级平台描述')),
            ],
            options={
                'db_table': 'config_address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegisterSubInfo',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=255, verbose_name='节点id')),
                ('pid', models.CharField(max_length=255, verbose_name='节点上级id')),
                ('ip', models.GenericIPAddressField()),
                ('type', models.SmallIntegerField(verbose_name='1-yihnac|2-manager')),
                ('username', models.CharField(max_length=255, verbose_name='为pid提供的用户')),
                ('password', models.CharField(max_length=255, verbose_name='用户对应的密码')),
                ('role', models.SmallIntegerField(verbose_name='用户对应的权值')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='行政地区')),
                ('net_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='网络名称')),
                ('des', models.CharField(blank=True, max_length=255, null=True, verbose_name='说明')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='注册时间')),
            ],
            options={
                'db_table': 'register_sub_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegisterSupInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
                ('register_pw', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('pid', models.CharField(max_length=255)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('des', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'register_sup_info',
                'managed': True,
            },
        ),
    ]
